export const plants = [
    {
        "Scientific_Name": "Aphelandra squarrosa",
        "Common_Name": "Zebra Plant",
        "img_name": "zebra_plant.png",
        "Sunlight": "Part shade to full shade",
        "Moisture": "Medium",
        "Soil_Indicator": "Never dry",
        "Plant_Spread": "4.00 to 5.00 feet",
        "Plant_Height": "4.00 to 6.00 feet",
        "Indoor_Spread": "1.00 to 1.75 feet",
        "Indoor_Height": "1.00 to 2.00 feet",
        "Toxic_Dogs": false,
        "Toxic_Cats": false,
        "Plant_Habit": "Herb/Forb/Shrub",
        "Type": "Broadleaf evergreen",
        "indoor_flowering": true,
        "hanging": false,
        "Bloom_Period": "Late Summer to Fall",
        "Humidity": "High",
        "Air_Purifying": "Unknown",
        "Ph_Soil": "Acidic",
        "Bloom_Description": "Yellow"
    },
    {
       "Scientific_Name": "Calathea zebrina",
       "Common_Name": "Calathea Zebra Plant",
       "img_name": "calathea_zebra_plant.png",
       "Sunlight": "Part shade to full shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Never dry",
       "Plant_Spread": "1.00 to 2.00 feet",
       "Plant_Height": "1.00 to 3.00 feet",
       "Indoor_Spread": "1.00 to 2.00 feet",
       "Indoor_Height": "1.00 to 3.00 feet",
       "Toxic_Dogs": false,
       "Toxic_Cats": false,
       "Plant_Habit": "Herb/Forb",
       "Type": "Herbaceous perennial",
       "indoor_flowering": "Rarely",
       "hanging": false,
       "Bloom_Period": "Mid Spring",
       "Humidity": "High",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Unknown",
       "Bloom_Description": "White/Purple"
    },
    {
       "Scientific_Name": "Crassula ovata",
       "Common_Name": "Jade Plant",
       "img_name": "jade_plant.png",
       "Sunlight": "Part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Dry",
       "Plant_Spread": "2.00 to 3.00 feet",
       "Plant_Height": "3.00 to 6.00 feet",
       "Indoor_Spread": "1.00 to 1.50 feet",
       "Indoor_Height": "1.50 to 3.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Cactus/Succulent",
       "Type": "Broadleaf evergreen",
       "indoor_flowering": "Rarely",
       "hanging": false,
       "Bloom_Period": "Spring",
       "Humidity": "Low to Moderate",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic, Neutral, Alkaline",
       "Bloom_Description": "White/Pink"
    },
    {
       "Scientific_Name": "Euphorbia milii",
       "Common_Name": "Crown of Thorns",
       "img_name": "crown_of_thorns.png",
       "Sunlight": "Full sun",
       "Moisture": "Low to medium",
       "Soil_Indicator": "Slightly dry",
       "Plant_Spread": "1.50 to 3.00 feet",
       "Plant_Height": "3.00 to 6.00 feet",
       "Indoor_Spread": "0.50 to 1.50 feet",
       "Indoor_Height": "0.50 to 2.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Shrub/Cactus/Succulent",
       "Type": "Broadleaf evergreen",
       "indoor_flowering": true,
       "hanging": false,
       "Bloom_Period": "Late Winter to Fall",
       "Humidity": "Low to High",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic, Neutral, Alkaline",
       "Bloom_Description": "Red"
    },
    {
       "Scientific_Name": "Ficus benjamina",
       "Common_Name": "Weeping Fig",
       "img_name": "weeping_fig.png",
       "Sunlight": "Full sun to part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Slightly dry",
       "Plant_Spread": "25.00 to 30.00 feet",
       "Plant_Height": "40.00 to 50.00 feet",
       "Indoor_Spread": "1.00 to 6.00 feet",
       "Indoor_Height": "2.00 to 10.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Shrub/Tree",
       "Type": "Broadleaf evergreen",
       "indoor_flowering": "Rarely",
       "hanging": false,
       "Bloom_Period": "Unknown",
       "Humidity": "Moderate to High",
       "Air_Purifying": true,
       "Ph_Soil": "Acidic",
       "Bloom_Description": "Black/Red/Orange"
    },
    {
       "Scientific_Name": "Cycas revoluta",
       "Common_Name": "Sago Palm",
       "img_name": "sago_palm.png",
       "Sunlight": "Full sun to part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Dry",
       "Plant_Spread": "3.00 to 10.00 feet",
       "Plant_Height": "3.00 to 10.00 feet",
       "Indoor_Spread": "0.50 to 2.00 feet ",
       "Indoor_Height": "0.50 to 2.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Shrub/Tree",
       "Type": "Palm/Cycad",
       "indoor_flowering": "N/A",
       "hanging": false,
       "Bloom_Period": "N/A",
       "Humidity": "Moderate to High",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic, Neutral",
       "Bloom_Description": "N/A"
    },
    {
       "Scientific_Name": "Tradescantia fluminensis",
       "Common_Name": "Wandering Jew",
       "img_name": "wandering_jew.png",
       "Sunlight": "Full sun to part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Dry",
       "Plant_Spread": "0.75 to 2.00 feet",
       "Plant_Height": "0.50 to 0.75 feet",
       "Indoor_Spread": "0.75 to 2.00 feet",
       "Indoor_Height": "2.00 to 6.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": false,
       "Plant_Habit": "Herb/Forb",
       "Type": "Herbaceous perennial",
       "indoor_flowering": "Rarely",
       "hanging": true,
       "Bloom_Period": "Year Round",
       "Humidity": "Moderate to High",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic, Neutral",
       "Bloom_Description": "White"
    },
    {
       "Scientific_Name": "Hoya lanceolata subsp. bella",
       "Common_Name": "Miniature Wax Plant",
       "img_name": "miniature_wax_plant.png",
       "Sunlight": "Full sun to part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Nearly dry",
       "Plant_Spread": "1.00 to 1.50 feet",
       "Plant_Height": "1.00 to 1.50 feet",
       "Indoor_Spread": "1.00 to 1.50 feet",
       "Indoor_Height": "1.00 to 1.50 feet",
       "Toxic_Dogs": "Unknown",
       "Toxic_Cats": "Unknown",
       "Plant_Habit": "Cactus/Succulent/Vine",
       "Type": "Broadleaf evergreen",
       "indoor_flowering": true,
       "hanging": false,
       "Bloom_Period": "Summer",
       "Humidity": "Moderate to High",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic, Neutral",
       "Bloom_Description": "White"
    },
    {
       "Scientific_Name": "Epipremnum aureum",
       "Common_Name": "Golden Pothos",
       "img_name": "golden_pothos.png",
       "Sunlight": "Part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Nearly dry",
       "Plant_Spread": "3.00 to 6.00 feet",
       "Plant_Height": "20.00 to 40.00 feet",
       "Indoor_Spread": "1.00 to 1.20 feet",
       "Indoor_Height": "6.00 to 8.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Herb/Forb",
       "Type": "Vine",
       "indoor_flowering": "Rarely",
       "hanging": true,
       "Bloom_Period": "Mid Summer",
       "Humidity": "Moderate",
       "Air_Purifying": true,
       "Ph_Soil": "Acidic",
       "Bloom_Description": "White"
    },
    {
       "Scientific_Name": "Sansevieria trifasciata",
       "Common_Name": "Snake Plant",
       "img_name": "snake_plant.png",
       "Sunlight": "Part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Dry",
       "Plant_Spread": "1.00 to 2.00 feet",
       "Plant_Height": "2.00 to 4.00 feet",
       "Indoor_Spread": "0.5 to 1.00 feet",
       "Indoor_Height": "0.50 to 2.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Herb/Forb",
       "Type": "Herbaceous perennial",
       "indoor_flowering": "Rarely",
       "hanging": false,
       "Bloom_Period": "Late Spring to Early Summer",
       "Humidity": "Moderate",
       "Air_Purifying": true,
       "Ph_Soil": "Alkaline, Neutral",
       "Bloom_Description": "White/Green"
    },
    {
       "Scientific_Name": "Maranta leuconeura",
       "Common_Name": "Prayer Plant",
       "img_name": "prayer_plant.png",
       "Sunlight": "Part shade to full shade",
       "Moisture": "High",
       "Soil_Indicator": "Never dry",
       "Plant_Spread": "0.50 to 1.00 feet",
       "Plant_Height": "0.50 to 1.00 feet",
       "Indoor_Spread": "0.50 to 1.00 feet",
       "Indoor_Height": "0.50 to 1.00 feet",
       "Toxic_Dogs": false,
       "Toxic_Cats": false,
       "Plant_Habit": "Herb/Forb",
       "Type": "Herbaceous perennial",
       "indoor_flowering": "Rarely",
       "hanging": true,
       "Bloom_Period": "Late Spring to Early Summer",
       "Humidity": "High",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic",
       "Bloom_Description": "White"
    },
    {
       "Scientific_Name": "Begonia Semperflorens Cultorum Group",
       "Common_Name": "Wax Plant Begonia",
       "img_name": "wax_plant_begonia.png",
       "Sunlight": "Full sun to part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Dry",
       "Plant_Spread": "0.50 to 1.00 feet",
       "Plant_Height": "0.50 to 1.00 feet",
       "Indoor_Spread": "0.50 to 1.00 feet",
       "Indoor_Height": "0.50 to 1.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Herb/Forb",
       "Type": "Herbaceous perennial",
       "indoor_flowering": true,
       "hanging": true,
       "Bloom_Period": "Year Round",
       "Humidity": "Moderate to High",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic, Neutral",
       "Bloom_Description": "White/Pink/Red"
    },
    {
       "Scientific_Name": "Schefflera arboricola",
       "Common_Name": "Umbrella Plant",
       "img_name": "umbrella_plant.png",
       "Sunlight": "Full sun to part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Dry",
       "Plant_Spread": "4.00 to 8.00 feet",
       "Plant_Height": "10.00 to 25.00 feet",
       "Indoor_Spread": "1.50 to 2.50 feet",
       "Indoor_Height": "4.00 to 8.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Shrub/Tree",
       "Type": "Broadleaf evergreen",
       "indoor_flowering": "Rarely",
       "hanging": false,
       "Bloom_Period": "Unknown",
       "Humidity": "Moderate",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic, Neutral, Alkaline",
       "Bloom_Description": "Red/Orange"
    },
    {
       "Scientific_Name": "Syngonium podophyllum",
       "Common_Name": "Arrowhead Plant",
       "img_name": "arrowhead_plant.png",
       "Sunlight": "Part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Nearly dry",
       "Plant_Spread": "1.00 to 2.00 feet",
       "Plant_Height": "3.00 to 6.00 feet",
       "Indoor_Spread": "1.00 to 2.00 feet",
       "Indoor_Height": "3.00 to 6.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Herb/Forb",
       "Type": "Vine",
       "indoor_flowering": "Rarely",
       "hanging": true,
       "Bloom_Period": "Unknown",
       "Humidity": "Moderate to High",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic, Neutral, Alkaline",
       "Bloom_Description": "White/Green"
    },
    {
       "Scientific_Name": "Davallia Fejeensis",
       "Common_Name": "Rabbit's Foot Fern",
       "img_name": "rabbit_foot_fern.png",
       "Sunlight": "Part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Never dry",
       "Plant_Spread": "1.00 to 4.00 feet",
       "Plant_Height": "1.00 to 3.00 feet",
       "Indoor_Spread": "1.00 to 4.00 feet",
       "Indoor_Height": "1.00 to 3.00 feet",
       "Toxic_Dogs": false,
       "Toxic_Cats": false,
       "Plant_Habit": "Fern",
       "Type": "Fern",
       "indoor_flowering": false,
       "hanging": false,
       "Bloom_Period": "N/A",
       "Humidity": "Moderate to High",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Unknown",
       "Bloom_Description": "N/A"
    },
    {
       "Scientific_Name": "Spathiphyllum",
       "Common_Name": "Peace Lily",
       "img_name": "peace_lily.png",
       "Sunlight": "Part shade to full shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Nearly dry",
       "Plant_Spread": "1.00 to 5.00 feet",
       "Plant_Height": "1.00 to 6.00 feet",
       "Indoor_Spread": "1.00 to 5.00 feet",
       "Indoor_Height": "1.00 to 6.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Herb/Forb",
       "Type": "Herbaceous perennial",
       "indoor_flowering": true,
       "hanging": false,
       "Bloom_Period": "Late Spring to Fall",
       "Humidity": "High",
       "Air_Purifying": true,
       "Ph_Soil": "Acidic, Neutral,Alkaline",
       "Bloom_Description": "White"
    },
    {
       "Scientific_Name": "Zamioculcas Zamifolia",
       "Common_Name": "ZZ plant",
       "img_name": "zz_plant.png",
       "Sunlight": "Part shade to full shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Slightly dry",
       "Plant_Spread": "2.00 to 3.00 feet",
       "Plant_Height": "2.00 to 3.00 feet",
       "Indoor_Spread": "2.00 to 3.00 feet",
       "Indoor_Height": "2.00 to 3.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Herb/Forb",
       "Type": "Herbaceous perennial",
       "indoor_flowering": "Rarely",
       "hanging": false,
       "Bloom_Period": "Year Round",
       "Humidity": "Low to Moderate",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Unknown",
       "Bloom_Description": "White/Green"
    },
    {
       "Scientific_Name": "Chamaedorea elegans",
       "Common_Name": "Parlor Palm",
       "img_name": "parlor_palm.png",
       "Sunlight": "Part shade to full shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Slightly dry",
       "Plant_Spread": "2.00 to 3.00 feet",
       "Plant_Height": "2.00 to 6.00 feet",
       "Indoor_Spread": "2.00 to 3.00 feet",
       "Indoor_Height": "2.00 to 6.00 feet",
       "Toxic_Dogs": false,
       "Toxic_Cats": false,
       "Plant_Habit": "Tree",
       "Type": "Palm/Cycad",
       "indoor_flowering": true,
       "hanging": false,
       "Bloom_Period": "Late Winter to Early Summer",
       "Humidity": "Moderate",
       "Air_Purifying": true,
       "Ph_Soil": "Acidic, Neutral",
       "Bloom_Description": "Yellow"
    },
    {
       "Scientific_Name": "Ficus elastica",
       "Common_Name": "Rubber Plant",
       "img_name": "rubber_plant.png",
       "Sunlight": "Part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Dry",
       "Plant_Spread": "3.00 to 5.00 feet",
       "Plant_Height": "3.00 to 9.00 feet",
       "Indoor_Spread": "3.00 to 5.00 feet",
       "Indoor_Height": "2.00 to 10.00 feet",
       "Toxic_Dogs": false,
       "Toxic_Cats": false,
       "Plant_Habit": "Tree",
       "Type": "Broadleaf evergreen",
       "indoor_flowering": "Rarely",
       "hanging": false,
       "Bloom_Period": "N/A",
       "Humidity": "High",
       "Air_Purifying": true,
       "Ph_Soil": "Acidic, Neutral",
       "Bloom_Description": "N/A"
    },
    {
       "Scientific_Name": "Cordyline fruticosa",
       "Common_Name": "Ti Plant",
       "img_name": "ti_plant.png",
       "Sunlight": "Part sun to part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Never dry",
       "Plant_Spread": "1.00 to 4.00 feet",
       "Plant_Height": "3.00 to 6.00 feet",
       "Indoor_Spread": "1.00 to 4.00 feet",
       "Indoor_Height": "3.00 to 8.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Shrub/Subshrub/Tree",
       "Type": "Broadleaf evergreen",
       "indoor_flowering": false,
       "hanging": false,
       "Bloom_Period": "N/A",
       "Humidity": "High",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic",
       "Bloom_Description": "N/A"
    },
    {
       "Scientific_Name": "Anthurium andraeanum",
       "Common_Name": "Flamingo Flower",
       "img_name": "flamingo_flower.png",
       "Sunlight": "Part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Nearly dry",
       "Plant_Spread": "0.75 to 1.00 feet",
       "Plant_Height": "1.00 to 1.50 feet",
       "Indoor_Spread": "0.75 to 1.00 feet",
       "Indoor_Height": "1.00 to 1.50 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Herb/Forb",
       "Type": "Herbaceous perennial",
       "indoor_flowering": true,
       "hanging": false,
       "Bloom_Period": "Summer to Early Fall",
       "Humidity": "High",
       "Air_Purifying": true,
       "Ph_Soil": "Acidic",
       "Bloom_Description": "Yellow"
    },
    {
       "Scientific_Name": "Ardisia crenata",
       "Common_Name": "Coral Berry",
       "img_name": "coral_berry.png",
       "Sunlight": "Part shade to full shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Never dry",
       "Plant_Spread": "4.00 to 5.00 feet",
       "Plant_Height": "4.00 to 5.00 feet",
       "Indoor_Spread": "4.00 to 5.00 feet",
       "Indoor_Height": "4.00 to 5.00 feet",
       "Toxic_Dogs": "Unknown",
       "Toxic_Cats": "Unknown",
       "Plant_Habit": "Shrub",
       "Type": "Broadleaf evergreen",
       "indoor_flowering": true,
       "hanging": false,
       "Bloom_Period": "Late Spring to Early Summer",
       "Humidity": "High",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic, Neutral, Alkaline",
       "Bloom_Description": "Red"
    },
    {
       "Scientific_Name": "Podocarpus macrophyllus",
       "Common_Name": "Buddhist Pine",
       "img_name": "buddhist_pine.png",
       "Sunlight": "Full sun to part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Slightly dry",
       "Plant_Spread": "20.00 to 40.00 fee",
       "Plant_Height": "10.00 to 20.00 feet",
       "Indoor_Spread": "2.00 to 4.00 feet",
       "Indoor_Height": "1.00 to 5.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Tree",
       "Type": "Needled evergreen",
       "indoor_flowering": false,
       "hanging": false,
       "Bloom_Period": "N/A",
       "Humidity": "Moderate",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic, Neutral, Alkaline",
       "Bloom_Description": "N/A"
    },
    {
       "Scientific_Name": "Phygelius x rectus",
       "Common_Name": "Cape fuchsia Cherry Ripe",
       "img_name": "cape_fuschia.png",
       "Sunlight": "Part shade to full shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Never dry",
       "Plant_Spread": "2.00 to 3.00 feet",
       "Plant_Height": "2.00 to 3.00 feet",
       "Indoor_Spread": "2.00 to 3.00 feet",
       "Indoor_Height": "2.00 to 3.00 feet",
       "Toxic_Dogs": false,
       "Toxic_Cats": false,
       "Plant_Habit": "Shrub",
       "Type": "Broadleaf evergreen",
       "indoor_flowering": true,
       "hanging": true,
       "Bloom_Period": "Spring",
       "Humidity": "Moderate",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic",
       "Bloom_Description": "Red"
    },
    {
       "Scientific_Name": "Impatiens capensis",
       "Common_Name": "Touch Me Not",
       "img_name": "touch_me_not.png",
       "Sunlight": "Part shade to full shade",
       "Moisture": "Medium to high",
       "Soil_Indicator": "Never dry",
       "Plant_Spread": "1.50 to 2.50 feet",
       "Plant_Height": "2.00 to 5.00 feet",
       "Indoor_Spread": "0.50 to 1.00 feet",
       "Indoor_Height": "1.50 to 2.00 feet",
       "Toxic_Dogs": false,
       "Toxic_Cats": false,
       "Plant_Habit": "Herb/Forb",
       "Type": "Annual Perennial",
       "indoor_flowering": true,
       "hanging": true,
       "Bloom_Period": "Mid Summer to Mid Fall",
       "Humidity": "Moderate",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic, Neutral, Alkaline",
       "Bloom_Description": "Orange/Orange-Yellow"
    },
    {
       "Scientific_Name": "Aloe vera",
       "Common_Name": "Aloe vera",
       "img_name": "aloe_vera.png",
       "Sunlight": "Full sun to part sun",
       "Moisture": "Low",
       "Soil_Indicator": "Slightly dry",
       "Plant_Spread": "0.50 to 1.00 feet",
       "Plant_Height": "1.00 to 2.00 feet",
       "Indoor_Spread": "0.50 to 1.00 feet",
       "Indoor_Height": "1.00 to 2.00 feet",
       "Toxic_Dogs": false,
       "Toxic_Cats": false,
       "Plant_Habit": "Cactus/Succulent",
       "Type": "Herbaceous perennial",
       "indoor_flowering": false,
       "hanging": false,
       "Bloom_Period": "N/A",
       "Humidity": "Low",
       "Air_Purifying": true,
       "Ph_Soil": "Neutral",
       "Bloom_Description": "N/A"
    },
    {
       "Scientific_Name": "Dracaena Braunii",
       "Common_Name": "Lucky Bamboo",
       "img_name": "lucky_bamboo.png",
       "Sunlight": "Part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Slightly dry",
       "Plant_Spread": "0.00 to 0.00 feet",
       "Plant_Height": "2.00 to 3.00 feet",
       "Indoor_Spread": "0.00 to 0.00 feet",
       "Indoor_Height": "2.00 to 3.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Graminoid",
       "Type": "Perennial",
       "indoor_flowering": false,
       "hanging": false,
       "Bloom_Period": "N/A",
       "Humidity": "Moderate",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic",
       "Bloom_Description": "N/A"
    },
    {
       "Scientific_Name": "Lobularia maritima",
       "Common_Name": "Sweet Alyssum",
       "img_name": "sweet_alyssum.png",
       "Sunlight": "Full sun to part sun",
       "Moisture": "Medium",
       "Soil_Indicator": "Never dry",
       "Plant_Spread": "0.00 to 1.00 feet",
       "Plant_Height": "0.50 to 1.00 feet",
       "Indoor_Spread": "0.00 to 0.75 feet",
       "Indoor_Height": "0.25 to 0.75 feet",
       "Toxic_Dogs": false,
       "Toxic_Cats": false,
       "Plant_Habit": "Herb/Forb",
       "Type": "Annual Perennial",
       "indoor_flowering": true,
       "hanging": true,
       "Bloom_Period": "Mid Spring to Early Summer",
       "Humidity": "Unknown",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic",
       "Bloom_Description": "White"
    },
    {
       "Scientific_Name": "Euphorbia pulcherrima",
       "Common_Name": "Poinsettia",
       "img_name": "poinsettia.png",
       "Sunlight": "Full sun to part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Never dry",
       "Plant_Spread": "3.00 to 7.00 feet",
       "Plant_Height": "3.00 to 10.00 feet",
       "Indoor_Spread": "1.00 to 3.00 feet",
       "Indoor_Height": "2.00 to 5.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Shrub",
       "Type": "Deciduous shrub",
       "indoor_flowering": true,
       "hanging": true,
       "Bloom_Period": "Mid Fall to Early Winter",
       "Humidity": "Moderate",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic",
       "Bloom_Description": "Red "
    },
    {
       "Scientific_Name": "Convallaria majuscula",
       "Common_Name": "Lily of the Valley",
       "img_name": "lily_of_the_valley.png",
       "Sunlight": "Part sun to part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Never dry",
       "Plant_Spread": "0.50 to 1.00 feet",
       "Plant_Height": "0.50 to 1.00 feet",
       "Indoor_Spread": "0.50 to 1.00 feet",
       "Indoor_Height": "0.50 to 1.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Herb/Forb",
       "Type": "Herbaceous perennial",
       "indoor_flowering": true,
       "hanging": false,
       "Bloom_Period": "Mid Spring to Early Summer",
       "Humidity": "Low",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic, Neutral",
       "Bloom_Description": "White/Pink "
    },
    {
       "Scientific_Name": "Gardenia jasminoides",
       "Common_Name": "Cape Jasmine",
       "img_name": "cape_jasmine.png",
       "Sunlight": "Full sun to part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Never dry",
       "Plant_Spread": "0.00 to 0.50 feet",
       "Plant_Height": "0.00 to 0.50 feet",
       "Indoor_Spread": "0.00 to 0.50 feet",
       "Indoor_Height": "1.00 to 3.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Shrub/Subshrub",
       "Type": "Broadleaf evergreen",
       "indoor_flowering": true,
       "hanging": true,
       "Bloom_Period": "Late Spring to Early Summer",
       "Humidity": "High",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic",
       "Bloom_Description": "White "
    },
    {
       "Scientific_Name": "Chrysanthemum ×morifolium",
       "Common_Name": "Chrysanthemum/Florist's daisy",
       "img_name": "chrysanthemum.png",
       "Sunlight": "Full sun",
       "Moisture": "Medium",
       "Soil_Indicator": "Never dry",
       "Plant_Spread": "2.00 to 3.00 feet",
       "Plant_Height": "1.50 to 2.00 feet",
       "Indoor_Spread": "2.00 to 3.00 feet",
       "Indoor_Height": "2.00 to 3.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Herb/Forb",
       "Type": "Herbaceous perennial",
       "indoor_flowering": true,
       "hanging": false,
       "Bloom_Period": "Fall to Late Winter",
       "Humidity": "Moderate",
       "Air_Purifying": true,
       "Ph_Soil": "Acidic",
       "Bloom_Description": "Yellow"
    },
    {
       "Scientific_Name": "Dypsis lutescens",
       "Common_Name": "Areca Palm",
       "img_name": "areca_palm.png",
       "Sunlight": "Part shade",
       "Moisture": "Low",
       "Soil_Indicator": "Slightly dry",
       "Plant_Spread": "8.00 to 15.00 feet",
       "Plant_Height": "12.00 to 30.00 feet",
       "Indoor_Spread": "1.25 to 4.00 feet",
       "Indoor_Height": "0.50 to 8.00 feet",
       "Toxic_Dogs": false,
       "Toxic_Cats": false,
       "Plant_Habit": "Tree",
       "Type": "Palm/Cycad",
       "indoor_flowering": true,
       "hanging": false,
       "Bloom_Period": "Summer",
       "Humidity": "Moderate",
       "Air_Purifying": true,
       "Ph_Soil": "Acidic",
       "Bloom_Description": "Yellow"
    },
    {
       "Scientific_Name": "Gerbera",
       "Common_Name": "Transvaal daisy",
       "img_name": "transvaal_daisy.png",
       "Sunlight": "Full sun to part shade",
       "Moisture": "Low",
       "Soil_Indicator": "Slightly dry",
       "Plant_Spread": "0.50 to 1.50 feet",
       "Plant_Height": "0.50 to 3.00 feet",
       "Indoor_Spread": "0.25 to 0.75 feet",
       "Indoor_Height": "1.00 to 1.50 feet",
       "Toxic_Dogs": false,
       "Toxic_Cats": false,
       "Plant_Habit": "Herb/Forb",
       "Type": "Herbaceous perennial",
       "indoor_flowering": true,
       "hanging": false,
       "Bloom_Period": "Late Spring to Late Summer",
       "Humidity": "Moderate",
       "Air_Purifying": true,
       "Ph_Soil": "Neutral",
       "Bloom_Description": "Multiple Colors"
    },
    {
       "Scientific_Name": "Mentha x piperita",
       "Common_Name": "Peppermint",
       "img_name": "peppermint.png",
       "Sunlight": "Full sun to part shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Never dry",
       "Plant_Spread": "1.00 to 1.5 feet",
       "Plant_Height": "0.50 to 1.00 feet",
       "Indoor_Spread": "0.50 to 0.75 feet",
       "Indoor_Height": "1.00 to 2.00 feet",
       "Toxic_Dogs": false,
       "Toxic_Cats": false,
       "Plant_Habit": "Herb/Forb",
       "Type": "Herbaceous perennial",
       "indoor_flowering": true,
       "hanging": false,
       "Bloom_Period": "Summer",
       "Humidity": "Moderate",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic, Neutral, Alkaline",
       "Bloom_Description": "Pink"
    },
    {
       "Scientific_Name": "Rosmarinus officinalis",
       "Common_Name": "Rosemary",
       "img_name": "rosemary.png",
       "Sunlight": "Full sun",
       "Moisture": "Medium",
       "Soil_Indicator": "Slightly dry",
       "Plant_Spread": "1.50 to 3.00 feet",
       "Plant_Height": "1.50 to 3.00 feet",
       "Indoor_Spread": "1.50 to 3.00 feet",
       "Indoor_Height": "3.00 to 4.00 feet",
       "Toxic_Dogs": false,
       "Toxic_Cats": false,
       "Plant_Habit": "Shurb/Vine",
       "Type": "Herbaceous perennial",
       "indoor_flowering": true,
       "hanging": true,
       "Bloom_Period": "Mid Winter to Mid Spring",
       "Humidity": "Moderate to High",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic",
       "Bloom_Description": "Blue"
    },
    {
       "Scientific_Name": "Jasminum officinale",
       "Common_Name": "Jasmine",
       "img_name": "jasmine.png",
       "Sunlight": "Full sun to part sun",
       "Moisture": "Medium",
       "Soil_Indicator": "Slightly dry",
       "Plant_Spread": "3.00 to 15.00 feet",
       "Plant_Height": "3.00 to 20.00 feet",
       "Indoor_Spread": "2.00 to 7.50 feet",
       "Indoor_Height": "2.00 to 10.00 feet",
       "Toxic_Dogs": false,
       "Toxic_Cats": false,
       "Plant_Habit": "Shrub",
       "Type": "Vine",
       "indoor_flowering": true,
       "hanging": false,
       "Bloom_Period": "Spring to Fall",
       "Humidity": "Moderate",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic, Neutral, Alkaline",
       "Bloom_Description": "White/Pale Pink"
    },
    {
       "Scientific_Name": "Hedera helix",
       "Common_Name": "English Ivy",
       "img_name": "english_ivy.png",
       "Sunlight": "Part shade to full shade",
       "Moisture": "Medium",
       "Soil_Indicator": "Never dry",
       "Plant_Spread": "3.00 to 13.00 feet",
       "Plant_Height": "20.00 to 80.00 feet",
       "Indoor_Spread": "0.50 to 1.00 feet",
       "Indoor_Height": "0.50 to 6.00 feet",
       "Toxic_Dogs": true,
       "Toxic_Cats": true,
       "Plant_Habit": "Shrub",
       "Type": "Vine",
       "indoor_flowering": false,
       "hanging": true,
       "Bloom_Period": "Fall",
       "Humidity": "High",
       "Air_Purifying": true,
       "Ph_Soil": "Acidic, Neutral, Alkaline",
       "Bloom_Description": "White/Green"
    },
    {
       "Scientific_Name": "Sempervivum tectorum ",
       "Common_Name": "House Leek",
       "img_name": "house_leek.png",
       "Sunlight": "Full sun",
       "Moisture": "Low to medium",
       "Soil_Indicator": "Dry",
       "Plant_Spread": "0.50 to 1.00 feet",
       "Plant_Height": "0.50 to 1.00 feet",
       "Indoor_Spread": "0.50 to 1.00 feet",
       "Indoor_Height": "0.50 to 1.00 feet",
       "Toxic_Dogs": false,
       "Toxic_Cats": false,
       "Plant_Habit": "Herb/Forb",
       "Type": "Herbaceous perennial",
       "indoor_flowering": true,
       "hanging": false,
       "Bloom_Period": "Summer",
       "Humidity": "Moderate",
       "Air_Purifying": "Unknown",
       "Ph_Soil": "Acidic, Neutral, Alkaline",
       "Bloom_Description": "Yellow"
    }
 ]