export const wellnessFactors = [
    {
        id: 1,
        title: 'Physical',
        image: 'https://thewellatsacstate.com/cache/ce-image/dimensions-of-wellness/uploads/images/7_dimensions/7D_Icon_Physical_500x500ppi_500_500_bor3_0fa195_all_250.png',
        color: 'red',
        description: 'Taking care of one\'s body.',
        stars: 4,
        isPriority: true,
    },
    {
        id: 2,
        title: 'Social',
        image: 'https://thewellatsacstate.com/cache/ce-image/dimensions-of-wellness/uploads/images/7_dimensions/7D_Icon_SocioCultural_500x500ppi_500_500_bor3_0fa195_all_250.png',
        color: 'purple',
        description: 'Effectively relating to others, your community and the world.',
        stars: 3,
        isPriority: false,
    },
    {
        id: 3,
        title: 'Organizational',
        image: 'https://thewellatsacstate.com/cache/ce-image/dimensions-of-wellness/uploads/images/7_dimensions/7D_Icon_SocioCultural_500x500ppi_500_500_bor3_0fa195_all_250.png',
        color: 'blue',
        description: 'Effectively relating to others, your community and the world.',
        stars: 5,
        isPriority: false,
    },
    {
        id: 4,
        title: 'Financial',
        image: 'https://thewellatsacstate.com/cache/ce-image/dimensions-of-wellness/uploads/images/7_dimensions/7D_Icon_CareerFinancial_500x500ppi_500_500_bor3_0fa195_all_250.png',
        color: 'teal',
        description: 'Engaging in meaningful work and responsible monetary practices.',
        stars: 7,
        isPriority: false,
    },
    {
        id: 5,
        title: 'Environmental',
        image: 'https://thewellatsacstate.com/cache/ce-image/dimensions-of-wellness/uploads/images/7_dimensions/7D_Icon_Environmental_500x500ppi_500_500_bor3_0fa195_all_250.png',
        color: 'green',
        description: 'Caring for the earth.',
        stars: 6,
        isPriority: false,
    },
    {
        id: 6,
        title: 'Spiritual',
        image: 'https://thewellatsacstate.com/cache/ce-image/dimensions-of-wellness/uploads/images/7_dimensions/7D_Icon_Spiritual_500x500ppi_500_500_bor3_0fa195_all_250.png',
        color: 'yellow',
        description: 'Exploring value and meaning in one\'s life.',
        stars: 5,
        isPriority: true,
    },
    {
        id: 7,
        title: 'Emotional',
        image: 'https://thewellatsacstate.com/cache/ce-image/dimensions-of-wellness/uploads/images/7_dimensions/7D_Icon_Emotional_500x500ppi_500_500_bor3_0fa195_all_250.png',
        color: 'orange',
        description: 'Awareness, acceptance & a healthy expression of one\'s feelings.',
        stars: 7,
        isPriority: false,
    },
    {
        id: 8,
        title: 'Intellectual',
        image: 'https://thewellatsacstate.com/cache/ce-image/dimensions-of-wellness/uploads/images/7_dimensions/7D_Icon_Intellectual_500x500ppi_500_500_bor3_0fa195_all_250.png',
        color: 'orangered',
        description: 'Developing & utilizing one\'s knowledge.',
        stars: 8,
        isPriority: true,
    },
]

export const resourceList = []